### ISSUE TITLE
nanica-builderがエラー時にcode 0で終了する

### ISSUE THREAD

**Issue by recuraki** [burioden/atcoder#1]
## なにか？
[nanica-builder](https://github.com/burioden/atcoder/tree/main/nanica-builder)がコンテストの生成を失敗した際に0以外を返すようにする。

## なぜ？
多くのプログラムは正常終了した際に0, 失敗した時に0以外を返します。(戻り値)本プログラムもそれに従って値を返すと良いと考えます。

## TODO
現行のエラー終了時に0以外を返すようにする。

**Comment by burioden** [comment]
ありがとうございます！競プロだけでは知れないことを教えていただきサンクスです！！
